/**
    * This file was auto-generated by openapi-typescript.
    * Do not make direct changes to the file.
*/
import { Api } from './api';

export class AuthApi extends Api {
  get userBotLoginPost() {
    return this.ft.path('/user/bot:login').method('post').create()!;
  }

  get userUser() {
    return this.ft.path('/user/user').method('get').create()!;
  }

  get userCheck() {
    return this.ft.path('/user/check').method('get').create()!;
  }

  get userUserLoginPost() {
    return this.ft.path('/user/user:login').method('post').create()!;
  }

  get userBindInviterPost() {
    return this.ft.path('/user/bind:inviter').method('post').create()!;
  }

  get userMsgToLogin() {
    return this.ft.path('/user/msg-to-login').method('get').create()!;
  }
}
