/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
import { Api } from './api';

export class BotApi extends Api {
  get userUsername() {
    return this.ft.path('/user/username').method('get').create()!;
  }

  get userCheck() {
    return this.ft.path('/user/check').method('get').create()!;
  }

  get userUserVoteDevices() {
    return this.ft.path('/user/user-vote-devices').method('get').create()!;
  }

  get userUserReward() {
    return this.ft.path('/user/user-reward').method('get').create()!;
  }

  get userRegisterPost() {
    return this.ft.path('/user/register').method('post').create()!;
  }

  get userInviterRecords() {
    return this.ft.path('/user/inviter-records').method('get').create()!;
  }

  get userUser() {
    return this.ft.path('/user/user').method('get').create()!;
  }

  get userRewardRank() {
    return this.ft.path('/user/reward:rank').method('get').create()!;
  }

  get userInviterRankFull() {
    return this.ft.path('/user/inviter/rank/full').method('get').create()!;
  }

  get userInviterRankWeek() {
    return this.ft.path('/user/inviter/rank/week').method('get').create()!;
  }

  get userNotifyPost() {
    return this.ft.path('/user/notify').method('post').create()!;
  }

  get userVoteDevices() {
    return this.ft.path('/user/vote:devices').method('get').create()!;
  }

  get userUserStrictPost() {
    return this.ft.path('/user/user/strict').method('post').create()!;
  }

  get userVerifyPost() {
    return this.ft.path('/user/verify').method('post').create()!;
  }

  get userPersonalInfoPost() {
    return this.ft.path('/user/personal/info').method('post').create()!;
  }

  get userChannelJoinedPost() {
    return this.ft.path('/user/channel/joined').method('post').create()!;
  }

  get drawCanWithdraw() {
    return this.ft.path('/draw/canWithdraw').method('get').create()!;
  }

  get drawDoPost() {
    return this.ft.path('/draw/do').method('post').create()!;
  }

  get drawChance() {
    return this.ft.path('/draw/chance').method('get').create()!;
  }

  get drawRecord() {
    return this.ft.path('/draw/record').method('get').create()!;
  }

  get drawWithdrawPost() {
    return this.ft.path('/draw/withdraw').method('post').create()!;
  }

  get drawWithdrawRecordPost() {
    return this.ft.path('/draw/withdraw-record').method('post').create()!;
  }

  get drawVerifyChancePost() {
    return this.ft.path('/draw/verify/chance').method('post').create()!;
  }

  get stakeDoPost() {
    return this.ft.path('/stake/do').method('post').create()!;
  }

  get stakeUnlockPost() {
    return this.ft.path('/stake/unlock').method('post').create()!;
  }

  get transferTblPost() {
    return this.ft.path('/transfer/tbl').method('post').create()!;
  }

  get assignmentListPost() {
    return this.ft.path('/assignment/list').method('post').create()!;
  }

  get assignmentVersion() {
    return this.ft.path('/assignment/version').method('get').create()!;
  }

  get assignmentDoPost() {
    return this.ft.path('/assignment/do').method('post').create()!;
  }

  get assignmentDailyDoPost() {
    return this.ft.path('/assignment/daily/do').method('post').create()!;
  }

  get assignmentDailyListPost() {
    return this.ft.path('/assignment/daily/list').method('post').create()!;
  }

  get assignmentDailyAssignmentPost() {
    return this.ft.path('/assignment/daily/assignment').method('post').create()!;
  }

  get assignmentDailyRepeatAssignmentPost() {
    return this.ft.path('/assignment/daily/repeat-assignment').method('post').create()!;
  }

  get twitterCheckPost() {
    return this.ft.path('/twitter/check').method('post').create()!;
  }

  get twitterCheckQueryPost() {
    return this.ft.path('/twitter/check/query').method('post').create()!;
  }

  get twitterCallbackGet() {
    return this.ft.path('/twitter/callback/get').method('get').create()!;
  }
}
