/**
    * This file was auto-generated by openapi-typescript.
    * Do not make direct changes to the file.
*/
import { Api } from './api';

export class Yapi extends Api {
  get userUser() {
    return this.ft.path('/user/user').method('get').create()!;
  }

  get userUserLoginPost() {
    return this.ft.path('/user/user:login').method('post').create()!;
  }

  get userMsgToLogin() {
    return this.ft.path('/user/msg-to-login').method('get').create()!;
  }

  get userInvitationRelations() {
    return this.ft.path('/user/invitation-relations').method('get').create()!;
  }

  get userInvitationRelation() {
    return this.ft.path('/user/invitation-relation').method('get').create()!;
  }

  get userInviterRebates() {
    return this.ft.path('/user/inviter-rebates').method('get').create()!;
  }

  get userRebateWithdrawRecords() {
    return this.ft.path('/user/rebate-withdraw-records').method('get').create()!;
  }

  get userRebateWithdrawRecord() {
    return this.ft.path('/user/rebate-withdraw-record').method('get').create()!;
  }

  get userRebateWithdrawPost() {
    return this.ft.path('/user/rebate:withdraw').method('post').create()!;
  }
}
