/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
import { Api } from './api';

export class Yapi extends Api {
  get commonDict() {
    return this.ft.path('/common/dict').method('get').create()!;
  }

  get rewardCrossRewardWithdrawPost() {
    return this.ft
      .path('/reward/cross-reward:withdraw')
      .method('post')
      .create()!;
  }

  get rewardCrossReward() {
    return this.ft.path('/reward/cross-reward').method('get').create()!;
  }

  get userAddressIntegral() {
    return this.ft.path('/user/address-integral').method('get').create()!;
  }

  get userIntegralRecords() {
    return this.ft.path('/user/integral-records').method('get').create()!;
  }

  get userInvitationRelationPost() {
    return this.ft.path('/user/invitation-relation').method('post').create()!;
  }

  get userUserCheck() {
    return this.ft.path('/user/user:check').method('get').create()!;
  }

  get userAddressIntegralsTop() {
    return this.ft.path('/user/address-integrals:top').method('get').create()!;
  }

  get userUser() {
    return this.ft.path('/user/user').method('get').create()!;
  }

  get userUserLoginPost() {
    return this.ft.path('/user/user:login').method('post').create()!;
  }

  get userDhcRecordSyncPost() {
    return this.ft.path('/user/dhc-record:sync').method('post').create()!;
  }

  get userTaskRecordSyncPost() {
    return this.ft.path('/user/task-record:sync').method('post').create()!;
  }

  get apiBridgeRecords() {
    return this.ft.path('/api/bridge-records').method('get').create()!;
  }

  get apiBridgeAddress() {
    return this.ft.path('/api/bridge-address').method('get').create()!;
  }

  get apiBridgeStatistics() {
    return this.ft.path('/api/bridge-statistics').method('get').create()!;
  }
}
