/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/users': {
    get: {
      parameters: {
        query: {
          /**
           * 页码
           * 从 1 开始
           * 不传默认为第一页
           */
          pageNo?: string;
          /**
           * 每页个数
           * 不传默认为 20
           * 最大为 1000
           */
          pageSize?: string;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string;
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string;
            /** @description 返回数据 */
            data: {
              /** @description 是否还有前一页 */
              hasPrev: boolean;
              /** @description 当前页码 */
              pageNo: number;
              /** @description 总页数 */
              totalPage: number;
              /** @description 每页个数 */
              pageSize: number;
              /** @description 是否还有后一页 */
              hasNext: boolean;
              /** @description 总数 */
              totalCount: number;
              /** @description 数据域 */
              items: {
                /** @description 用户用户地址 */
                userAddress?: string;
                /** @description 用户唯一邀请码 */
                userInvitationCode?: string;
                /** @description 用户名称 */
                userName?: string;
                /** @description 用户ID */
                userID?: number;
                /** @description 用户邀请人地址 */
                userInvitationAddress?: string;
              }[];
            };
          };
        };
      };
    };
  };
  '/user/user': {
    get: {
      parameters: {};
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            msg: string;
            data: {
              userID: string;
              userAddress: string;
              userInvitationCode: string;
              userInvitationAddress: string;
            };
            fail: boolean;
          };
        };
      };
    };
  };
  '/user/user:login': {
    post: {
      parameters: {
        body: {
          root?: {
            address: string;
            signature: string;
            invitationCode?: string;
            message: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            msg: string;
            data: string;
            fail: boolean;
          };
        };
      };
    };
  };
  '/user/msg-to-login': {
    get: {
      parameters: {};
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            msg: string;
            data: string;
            fail: boolean;
          };
        };
      };
    };
  };
  '/user/invitation-relations': {
    get: {
      parameters: {
        query: {
          /**
           * 页码
           * 从 1 开始
           * 不传默认为第一页
           */
          pageNo?: string;
          /**
           * 每页个数
           * 不传默认为 20
           * 最大为 1000
           */
          pageSize?: string;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string;
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string;
            /** @description 返回数据 */
            data: {
              /** @description 是否还有前一页 */
              hasPrev: boolean;
              /** @description 当前页码 */
              pageNo: number;
              /** @description 总页数 */
              totalPage: number;
              /** @description 每页个数 */
              pageSize: number;
              /** @description 是否还有后一页 */
              hasNext: boolean;
              /** @description 总数 */
              totalCount: number;
              /** @description 数据域 */
              items: {
                /** @description 邀请记录名称 */
                invitationRelationName?: string;
                /** @description 邀请记录ID */
                invitationRelationID?: number;
                /** @description 邀请记录被邀请人地址 */
                invitationRelationInviteeAddress?: string;
                /** @description 邀请记录邀请人地址 */
                invitationRelationInviterAddress?: string;
                /** @description 邀请记录邀请等级 */
                invitationRelationInviterLevel?: string;
                /** @description 邀请记录邀请时间 */
                invitationRelationInviterTime?: string;
              }[];
            };
          };
        };
      };
    };
  };
  '/user/invitation-relation': {
    get: {
      parameters: {
        query: {
          /** 邀请记录ID */
          invitationRelationID: string;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string;
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string;
            /** @description 返回数据 */
            data: {
              /** @description 邀请记录名称 */
              invitationRelationName: string;
              /** @description 邀请记录ID */
              invitationRelationID: number;
              /** @description 邀请记录被邀请人地址 */
              invitationRelationInviteeAddress: string;
              /** @description 邀请记录邀请人地址 */
              invitationRelationInviterAddress: string;
              /** @description 邀请记录邀请等级 */
              invitationRelationInviterLevel: string;
              /** @description 邀请记录邀请时间 */
              invitationRelationInviterTime: string;
            };
          };
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 请求参数 */
          root?: {
            /** @description 名称 */
            name: string;
            /** @description 被邀请人地址 */
            inviteeAddress: string;
            /** @description 邀请等级 */
            inviterLevel: string;
            /** @description 邀请人地址 */
            inviterAddress: string;
            /** @description 邀请时间 */
            inviterTime: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string;
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string;
            /** @description 返回数据 */
            data: { [key: string]: unknown };
          };
        };
      };
    };
  };
}

export interface operations {}

export interface external {}
