export const ChainConfig = {
  ethereum: {
    id: '0x1',
    token: 'ETH',
    label: 'Ethereum',
    rpcUrl: 'https://rpc.ankr.com/eth',
    scanUrl: 'https://etherscan.com',
  },
  goerli: {
    id: '0x5',
    token: 'ETH',
    label: 'ETH Goerli',
    rpcUrl: 'https://rpc.ankr.com/eth_goerli',
    scanUrl: 'https://goerli.etherscan.io',
  },
  sepolia: {
    id: '0xaa36a7',
    token: 'ETH',
    label: 'ETH Sepolia',
    rpcUrl: 'https://eth-sepolia-public.unifra.io',
    scanUrl: 'https://sepolia.etherscan.io',
  },
  bsc: {
    id: '0x38',
    token: 'BNB',
    label: 'BSC',
    rpcUrl: 'https://rpc.ankr.com/bsc',
    scanUrl: 'https://bscscan.com',
  },
  bsc_testnet: {
    id: '0x61',
    token: 'BNB',
    label: 'BSC Chapel',
    rpcUrl:
            'https://bsc-testnet.nodereal.io/v1/e9a36765eb8a40b9bd12e680a1fd2bc5',
    scanUrl: 'https://testnet.bscscan.com',
  },
  polygon: {
    id: '0x89',
    token: 'MATIC',
    label: 'Polygon',
    rpcUrl: 'https://rpc.ankr.com/polygon',
    scanUrl: 'https://polygonscan.com',
  },
  mumbai: {
    id: '0x13881',
    token: 'MATIC',
    label: 'Polygon Mumbai',
    rpcUrl: 'https://rpc.ankr.com/polygon_mumbai',
    scanUrl: 'https://mumbai.polygonscan.com',
  },
  arbitrum_sepolia: {
    id: '0x66eee',
    token: 'ETH',
    label: 'Arbitrum Sepolia',
    rpcUrl: 'https://sepolia-rollup.arbitrum.io/rpc',
    scanUrl: 'https://sepolia.arbiscan.io',
  },
  arbitrum: {
    id: '0xa4b1',
    token: 'ETH',
    label: 'Arbitrum',
    rpcUrl: 'https://rpc.ankr.com/arbitrum',
    scanUrl: 'https://arbiscan.io',
  },
  optimism: {
    id: '0xa',
    token: 'ETH',
    label: 'Optimism',
    rpcUrl: 'https://rpc.ankr.com/optimism',
    scanUrl: 'https://optimistic.etherscan.io',
  },
  optimism_sepolia: {
    id: '0xaa37dc',
    token: 'ETH',
    label: 'Optimism Sepolia',
    rpcUrl: 'https://sepolia.optimism.io',
    scanUrl: 'https://sepolia-optimistic.etherscan.io',
  },
  filecoin_hyperspace: {
    id: '0xc45',
    token: 'tFIL',
    label: 'Filecoin Hyperspace',
    rpcUrl: 'https://rpc.ankr.com/filecoin_testnet',
    scanUrl: 'https://hyperspace.filfox.info',
  },
  zksync: {
    id: '0x144',
    label: 'zkSync',
    rpcUrl: 'https://rpc.ankr.com/zksync_era',
    token: 'ETH',
    scanUrl: 'https://explorer.zksync.io',
  },
  zksync_testnet: {
    id: '0x118',
    label: 'zkSync Testnet',
    rpcUrl: 'https://rpc.ankr.com/zksync_era_testnet',
    token: 'ETH',
    scanUrl: 'https://goerli.explorer.zksync.io',
  },
  avalanche: {
    id: '0xa86a',
    label: 'Avalanche',
    rpcUrl: 'https://rpc.ankr.com/avalanche',
    token: 'AVAX',
    scanUrl: 'https://subnets.avax.network/c-chain',
  },
  avalanche_fuji: {
    id: '0xa869',
    label: 'Avalanche Fuji',
    rpcUrl: 'https://rpc.ankr.com/avalanche_fuji',
    token: 'AVAX',
    scanUrl: 'https://subnets-test.avax.network/c-chain',
  },
  linea_testnet: {
    id: '0xe704',
    label: 'Linea goerli',
    rpcUrl: 'https://rpc-product.safematrix.io/json-rpc/http/linea_testnet',
    token: 'ETH',
    scanUrl: 'https://goerli.lineascan.build',
  },
  pego_test: {
    id: '0x1e240',
    label: 'Pego Testnet',
    rpcUrl: 'https://rpc-product.safematrix.io/json-rpc/http/pego_test',
    token: 'PG',
    scanUrl: 'https://scan.pegotest.net',
  },
  linea: {
    id: '0xe708',
    label: 'LINEA',
    token: 'ETH',
    rpcUrl: 'https://1rpc.io/linea',
    scanUrl: 'https://lineascan.build',
  },
  base_sepolia: {
    id: '0x14a34',
    label: 'Base Sepolia',
    rpcUrl: 'https://rpc.ankr.com/base_sepolia',
    token: 'ETH',
    scanUrl: 'https://sepolia.basescan.org',
  },
  base: {
    id: '0x2105',
    label: 'BASE',
    rpcUrl: 'https://rpc.ankr.com/base',
    token: 'ETH',
    scanUrl: 'https://basescan.org',
  },
  scroll: {
    id: '0x82750',
    label: 'SCROLL',
    rpcUrl: 'https://rpc.ankr.com/scroll',
    token: 'ETH',
    scanUrl: 'https://scrollscan.com',
  },
  chainx: {
    id: '0x5dd',
    label: 'BEVM',
    rpcUrl: 'https://rpc-1.bevm.io',
    token: 'BTC',
    scanUrl: 'https://scan.bevm.io',
  },
  x1_testnet: {
    id: '0xc3',
    token: 'OKB',
    label: 'X1 Testnet',
    rpcUrl: 'https://testrpc.x1.tech',
    scanUrl: 'https://www.oklink.com/x1-test',
  },
  bsquared: {
    id: '0xdf',
    token: 'BTC',
    label: 'B² Mainnet',
    rpcUrl: 'https://rpc.bsquared.network/',
    scanUrl: 'https://explorer.bsquared.network',
  },
  bitlayer: {
    id: '0x310c5',
    token: 'BTC',
    label: 'Bitlayer',
    rpcUrl: 'https://rpc.bitlayer.org/',
    scanUrl: 'https://www.btrscan.com',
  },
};
