/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/user/bot:login': {
    post: {
      parameters: {
        body: {
          root?: {
            data: string;
            hash: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            msg: string;
            data: string;
            fail: boolean;
          };
        };
      };
    };
  };
  '/user/user': {
    get: {
      parameters: {};
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            msg: string;
            data: {
              userID: string;
              userAddress: string;
              /** @description 用户来源 */
              userSource: string;
              /** @description 用户邀请码 */
              userInvitationCode: string;
              /** @description 用户上级地址 */
              userInvitationAddress: string;
              /** @description 用户一级邀请数量 */
              inviterL1Count: string;
              /** @description 用户二级邀请数量 */
              inviterL2Count: string;
              /** @description 用户一二级昨日质押量 */
              inviterStakingAmount: string;
              /** @description 用户自身质押量 */
              oneselfStakingAmount: string;
              /** @description 用户是否达到返佣最小质押量 */
              computeTag: boolean;
              /** @description 返佣已提现金额 */
              rebateWithdrawAmount: number;
              /** @description 用户返佣提现数量 */
              rebateBalanceMap: {
                /** @description 一级返佣可提现余额 */
                INVITER_L1: string;
                /** @description 二级返佣可提现余额 */
                INVITER_L2: string;
              };
            };
            fail: boolean;
          };
        };
      };
    };
  };
  '/user/check': {
    get: {
      parameters: {
        query: {
          address: string;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            msg: string;
            data: boolean;
            fail: boolean;
          };
        };
      };
    };
  };
  '/user/user:login': {
    post: {
      parameters: {
        body: {
          root?: {
            address: string;
            signature: string;
            invitationCode?: string;
            message: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            msg: string;
            data: string;
            fail: boolean;
          };
        };
      };
    };
  };
  '/user/bind:inviter': {
    post: {
      parameters: {
        body: {
          root?: {
            invitationCode: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            msg: string;
            data: string;
            fail: boolean;
          };
        };
      };
    };
  };
  '/user/msg-to-login': {
    get: {
      parameters: {};
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            msg: string;
            data: string;
            fail: boolean;
          };
        };
      };
    };
  };
}

export interface operations { }

export interface external { }

export type UserBotLoginPostParams = paths['/user/bot:login']['post']['parameters']['body']['root'];
export type UserBotLoginPost = paths['/user/bot:login']['post']['responses'][200]['schema']['data'];
export type UserUserGetParams = paths['/user/user']['get']['parameters'];
export type UserUser = paths['/user/user']['get']['responses'][200]['schema']['data'];
export type UserCheckGetParams = paths['/user/check']['get']['parameters']['query'];
export type UserCheck = paths['/user/check']['get']['responses'][200]['schema']['data'];
export type UserUserLoginPostParams = paths['/user/user:login']['post']['parameters']['body']['root'];
export type UserUserLoginPost = paths['/user/user:login']['post']['responses'][200]['schema']['data'];
export type UserBindInviterPostParams = paths['/user/bind:inviter']['post']['parameters']['body']['root'];
export type UserBindInviterPost = paths['/user/bind:inviter']['post']['responses'][200]['schema']['data'];
export type UserMsgToLoginGetParams = paths['/user/msg-to-login']['get']['parameters'];
export type UserMsgToLogin = paths['/user/msg-to-login']['get']['responses'][200]['schema']['data'];
