/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/user/username': {
    get: {
      parameters: {};
      responses: {
        /** successful operation */
        200: {
          schema: unknown;
        };
      };
    };
  };
  '/user/check': {
    get: {
      parameters: {
        query: {
          tgId?: string;
          username?: string;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: number;
            message: string;
            data: boolean;
          };
        };
      };
    };
  };
  '/user/user-vote-devices': {
    get: {
      parameters: {
        query: {
          address: string;
          pageNo: number;
          pageSize: number;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            message?: string;
            code?: number;
            data?: {
              pages?: number;
              current?: number;
              size?: number;
              total?: number;
              records?: {
                deviceStateTimeOnChain: string;
                deviceState: string;
                deviceID: string;
                deviceOwnerAddress: string;
                deviceRegisterTimeOnChain: string;
                deviceTotalStake: string;
                deviceOwnerStake: string;
                voterCount: number;
                nextVoterCount: number;
                deviceMyStake: string;
                lastHeartBeat: string;
                perBill: string;
                currentStake: string;
                nextStake: string;
                yield: string;
              }[];
            };
          };
        };
      };
    };
  };
  '/user/user-reward': {
    get: {
      parameters: {
        query: {
          ownerAddress: string;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code?: number;
            message?: string;
            data?: string;
          };
        };
      };
    };
  };
  '/user/register': {
    post: {
      parameters: {
        body: {
          root?: {
            hash: string;
            data: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: number;
            message: string;
            data: string;
          };
        };
      };
    };
  };
  '/user/inviter-records': {
    get: {
      parameters: {
        query: {
          /** 当前页 */
          pageNo: number;
          /** 每页数量 */
          pageSize: number;
          /** 用户ID */
          userId: string;
          /** 级别 1和2 */
          level: string;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: number;
            message: string;
            data: {
              records: {
                inviteeUsername: string;
                rewardValue: number;
                inviteTime: number;
                /** @description 是否验证 */
                verify: string;
                /** @description 用户自定义链接 */
                personalUrl: string;
              }[];
              total: number;
              size: number;
              current: number;
              pages: number;
              /** @description 验证过人数 */
              verifyCount: number;
            };
          };
        };
      };
    };
  };
  '/user/user': {
    get: {
      parameters: {
        query: {
          /** telegram user id */
          tgId: string;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: number;
            message: string;
            data: {
              /** @description evm 地址 */
              evmAddress: string;
              /** @description 用户id */
              userId: string;
              /** @description telegram username */
              username: string;
              /** @description 邀请码 */
              inviterCode: string;
              /** @description 用户排名 */
              rank: string;
              /** @description 总邀请人数 */
              inviterCount: number;
              /** @description 总奖励数量 */
              rewardValue: number;
              /** @description 注册分数 json */
              score: string;
              /** @description 是否已经加入过官方社群 */
              isJoinCommunity: boolean;
              /** @description 奖励记录map。key: type, value :amount */
              rewardMap: {
                ACCOUNT: string;
                INVITER: string;
                TASK: string;
                AMBASSADOR_INCENTIVE: string;
                AMBASSADOR: string;
              };
              /** @description 获奖总额(U) */
              prizeAmount: string;
              /** @description 是否认证为有价值用户 */
              isVerify: boolean;
              /** @description 个人url地址 */
              personalUrl: string;
            };
          };
        };
      };
    };
  };
  '/user/reward:rank': {
    get: {
      parameters: {
        query: {
          pageNo: number;
          pageSize: number;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: number;
            message: string;
            data: {
              records: {
                username: string;
                rank: string;
                rewardValue: number;
                /** @description 是否认证为有价值用户 */
                isVerify: boolean;
                /** 个人url地址 */
                personalUrl: string;
              }[];
              total: number;
              size: number;
              current: number;
              pages: number;
            };
          };
        };
      };
    };
  };
  '/user/inviter/rank/full': {
    get: {
      parameters: {
        query: {
          pageNo: number;
          pageSize: number;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code?: number;
            message?: string;
            data?: {
              records?: {
                /** @description 用户名称 */
                userName: string;
                /** @description 用户ID */
                userId: string;
                /** @description 邀请人数 */
                inviterNumbers: number;
                /** @description 一级邀请人数 */
                inviterNumbers1: number;
                /** @description 二级邀请人数 */
                inviterNumbers2: number;
                /** @description 排名 */
                ranking: number;
                /** @description 是否领取徽章 */
                verify: boolean;
                /** @description 用户自定义链接 */
                personalUrl: string;
              }[];
              total?: number;
              size?: number;
              current?: number;
              pages?: number;
            };
          };
        };
      };
    };
  };
  '/user/inviter/rank/week': {
    get: {
      parameters: {
        query: {
          pageNo: number;
          pageSize: number;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code?: number;
            message?: string;
            data?: {
              records?: {
                /** @description 用户名称 */
                userName: string;
                /** @description 用户ID */
                userId: string;
                /** @description 邀请人数 */
                inviterNumbers: number;
                /** @description 一级邀请人数 */
                inviterNumbers1: number;
                /** @description 二级邀请人数 */
                inviterNumbers2: number;
                /** @description 排名 */
                ranking: number;
                /** @description 是否领取徽章 */
                verify: string;
                /** @description 用户自定义链接 */
                personalUrl: string;
                /** @description 奖励，单位U */
                award: number;
              }[];
              total?: number;
              size?: number;
              current?: number;
              pages?: number;
            };
          };
        };
      };
    };
  };
  '/user/notify': {
    post: {
      parameters: {
        body: {
          root?: {
            userId: number;
            amount: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            msg: string;
            data: string;
          };
        };
      };
    };
  };
  '/user/vote:devices': {
    get: {
      parameters: {
        query: {
          /** 用户地址 */
          address?: string;
          pageNo: number;
          pageSize: number;
          /** 1：由高到低；0：由低到高 */
          voters?: string;
          /** 1：由高到低；0：由低到高 */
          totalStake?: string;
          /** 1：由高到低；0：由低到高 */
          yield?: string;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            message?: string;
            code?: number;
            data: {
              pages: number;
              current: number;
              size: number;
              total: number;
              records: {
                deviceStateTimeOnChain: string;
                deviceState: string;
                deviceID: string;
                deviceOwnerAddress: string;
                deviceRegisterTimeOnChain: string;
                deviceTotalStake: string;
                deviceOwnerStake: string;
                voterCount: number;
                nextVoterCount: number;
                deviceMyStake: string;
                lastHeartBeat: string;
                perBill: string;
                currentStake: string;
                nextStake: string;
                yield: string;
              }[];
            };
          };
        };
      };
    };
  };
  '/user/user/strict': {
    post: {
      parameters: {
        body: {
          root?: {
            /** 加密字符串 */
            hash?: string;
            /** 校验信息 */
            data?: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code?: number;
            message?: string;
            data?: {
              evmAddress?: string;
              userId?: string;
              username?: string;
              photoUrl?: unknown;
              inviterCode?: string;
              rank?: string;
              inviterCount?: number;
              rewardValue?: string;
              score?: string;
              rewardMap?: {
                INVITER?: string;
                TASK?: string;
                STAKING?: string;
                AMBASSADOR?: string;
                ACCOUNT?: string;
                DRAW?: string;
                RANKING?: string;
              };
              prizeAmount?: string;
              isVerify?: boolean;
              personalUrl?: string;
              chanceVerify?: boolean;
              /** @description 周榜排名 */
              weekRank: number;
              weekAmount1: number;
              weekAmount2: number;
            };
          };
        };
      };
    };
  };
  '/user/verify': {
    post: {
      parameters: {
        body: {
          root?: {
            hash: string;
            data: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: number;
            message: string;
            data: boolean;
          };
        };
      };
    };
  };
  '/user/personal/info': {
    post: {
      parameters: {
        body: {
          root?: {
            /** 个人链接 */
            personalUrl: string;
            /** 用户加密hash */
            hash: string;
            /** 校验data */
            data: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            /** 返回码 */
            code: number;
            /** 消息 */
            message: string;
            /** 是否成功 */
            data: boolean;
          };
        };
      };
    };
  };
  '/user/channel/joined': {
    post: {
      parameters: {
        body: {
          root?: {
            /** 校验hash */
            hash: string;
            /** 校验data */
            data: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            /** 错误码 */
            code: number;
            /** 错误消息 */
            message: string;
            /** 是否加群 */
            data: boolean;
          };
        };
      };
    };
  };
  '/draw/canWithdraw': {
    get: {
      parameters: {
        query: {
          /** 用户ID */
          userId: string;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: number;
            message: string;
            /**
                         * 可提取金额
                         * @description 小数
                         */
            data: number;
          };
        };
      };
    };
  };
  '/draw/do': {
    post: {
      parameters: {
        body: {
          root?: {
            /** 用户ID */
            userId: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            message: string;
            data: {
              /** 用户ID */
              userId: string;
              /**
                             * 中奖数量
                             * @description 未中奖则为0
                             */
              amount: string;
              /**
                             * 是否中奖
                             * @description 中奖为true 未中未false
                             */
              success: string;
            };
          };
        };
      };
    };
  };
  '/draw/chance': {
    get: {
      parameters: {
        query: {
          /** 用户ID */
          userId: string;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            /** code */
            code: number;
            /** message */
            message: string;
            /** 数据对象 */
            data: {
              /** 用户ID */
              userId: string;
              /** 抽奖机会余额 */
              balance: number;
            };
          };
        };
      };
    };
  };
  '/draw/record': {
    get: {
      parameters: {
        query: {
          /** 当前页码 */
          pageNo: number;
          /** 分页大小 */
          pageSize: number;
          /** 用户ID，可不填，不填就是全量记录 */
          userId?: string;
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            message: string;
            data: {
              total: number;
              size: number;
              current: number;
              pages: number;
              records: {
                /** 用户ID */
                userId: string;
                /** 用户名 */
                userName: string;
                /** 中奖时间 */
                timestamp: number;
                /** 数量 */
                amount: string;
              }[];
            };
          };
        };
      };
    };
  };
  '/draw/withdraw': {
    post: {
      parameters: {
        body: {
          root?: {
            /**
                         * 用户ID
                         * @description 用户ID，如果传这个值，就是走mpc钱包，不走自定义钱包
                         */
            userId?: string;
            /**
                         * 用户加密hash
                         * @description 如果userId不为空，可不传
                         */
            hash?: string;
            /** 交易data */
            data?: string;
            /** 用户自定义钱包地址 */
            address?: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            message: string;
            data: {
              /** 交易hash */
              txHash: string;
              /** 提取数量 */
              amount: string;
              /** 是否成功 */
              success: boolean;
              /** 浏览器地址 */
              scanUrl: string;
              /** 所属区块链 */
              chain: string;
            };
          };
        };
      };
    };
  };
  '/draw/withdraw-record': {
    post: {
      parameters: {
        body: {
          root?: {
            /** 提币地址 */
            address?: string;
            /** 用户加密hash */
            hash: string;
            /** 用户校验data */
            data: string;
            /** 页码 */
            pageNo?: number;
            /** 分页大小 */
            pageSize?: number;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code?: number;
            message?: string;
            data?: {
              records?: {
                username: string;
                userId: string;
                chain: string;
                withdrawTime: string;
                token: string;
                amount: string;
                address: string;
              }[];
              total?: number;
              size?: number;
              current?: number;
              pages?: number;
            };
          };
        };
      };
    };
  };
  '/draw/verify/chance': {
    post: {
      parameters: {
        body: {
          root?: {
            /** 用户ID */
            userId: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
                         * 返回码
                         * @description 52340 用户信息丢失
                         * 52350 用户无徽章
                         */
            code: string;
            /** 错误消息 */
            message: string;
            data: {
              /** 用户ID */
              userId: string;
              /** 当前领取的次数 */
              amount: number;
              /** 是否领取成功 */
              success: boolean;
            };
          };
        };
      };
    };
  };
  '/stake/do': {
    post: {
      parameters: {
        body: {
          root?: {
            /** @description 顺序要与deviceId一致 */
            amount: string[];
            deviceId: string[];
            /** 校验字符串 */
            hash: string;
            /** 校验数据 */
            data: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            /** 返回码 */
            code: number;
            /** 错误消息 */
            message: string;
            /** 签好的交易数据 */
            data: string;
          };
        };
      };
    };
  };
  '/stake/unlock': {
    post: {
      parameters: {
        body: {
          root?: {
            /** 校验hash */
            hash: string;
            /** 校验数据 */
            data: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            /** 返回码 */
            code: string;
            /** 消息 */
            message: string;
            /** 上链数据 */
            data: string;
          };
        };
      };
    };
  };
  '/transfer/tbl': {
    post: {
      parameters: {
        body: {
          root?: {
            /** 数量 */
            amount: string;
            /** 接收人地址 */
            reciever: string;
            /** 校验字符串 */
            hash: string;
            /** 校验数据 */
            data: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            /** 返回码 */
            code: number;
            /** 错误消息 */
            message: string;
            /** 签好的交易数据 */
            data: string;
          };
        };
      };
    };
  };
  '/assignment/list': {
    post: {
      parameters: {
        body: {
          root?: {
            /** 加密字符串 */
            hash?: string;
            /** 交易信息 */
            data?: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            message: string;
            data: {
              /** 任务ID */
              assignmentId: number;
              /** 任务标题 */
              title: string;
              /** 任务描述 */
              describe: string;
              /** 跳转链接 */
              url: string;
              /** 是否完成 */
              done: boolean;
              /** 奖励 */
              reward: string;
              /** 项目方 */
              project: string;
              /** logo url */
              logo?: string;
              /** 完成数量 */
              complete: string;
              /** 是否置顶 */
              top: boolean;
              /** 任务变更时间戳,毫秒 */
              timestamp: number;
            }[];
          };
        };
      };
    };
  };
  '/assignment/version': {
    get: {
      parameters: {};
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            message: string;
            /** 版本号，0不需要刷新 */
            data: number;
          };
        };
      };
    };
  };
  '/assignment/do': {
    post: {
      parameters: {
        body: {
          root?: {
            /** 用户校验字符串 */
            hash?: string;
            /** 校验数据 */
            data?: string;
            /** 任务ID */
            assignmentId?: number;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
                         * @description 52339 用户校验信息丢失
                         * 52340 未查找到该用户
                         * 52341 用户校验失败
                         * 52343 操作频繁
                         * 52348 助力校验结果为失败，用户未助力
                         * 52334 代码逻辑异常
                         * 52349 未加入群组
                         */
            code: number;
            message: string;
            /** 是否成功 */
            data: boolean;
          };
        };
      };
    };
  };
  '/assignment/daily/do': {
    post: {
      parameters: {
        body: {
          root?: {
            data: string;
            hash: string;
            assignmentId: number;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: number;
            message: string;
            data: boolean;
          };
        };
      };
    };
  };
  '/assignment/daily/list': {
    post: {
      parameters: {
        body: {
          root?: {
            /** 加密字符串 */
            hash?: string;
            /** 交易信息 */
            data?: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: number;
            message: string;
            data: {
              assignmentId: number;
              title: string;
              describe: string;
              url: string;
              done: boolean;
              level: number;
              signDay: number;
              reward: string;
              project: string;
              logo: string;
              top: boolean;
              sort: number;
            }[];
          };
        };
      };
    };
  };
  '/assignment/daily/assignment': {
    post: {
      parameters: {
        body: {
          root?: {
            data: string;
            hash: string;
            assignmentId: number;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: number;
            message: string;
            data: boolean;
          };
        };
      };
    };
  };
  '/assignment/daily/repeat-assignment': {
    post: {
      parameters: {
        body: {
          root?: {
            /** 加密字符串 */
            hash?: string;
            /** 交易信息 */
            data?: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: number;
            message: string;
            data: {
              assignmentId: number;
              title: string;
              describe: string;
              url: string;
              done: boolean;
              reward: string;
              project: string;
              logo: string;
              top: boolean;
              sort: number;
            }[];
          };
        };
      };
    };
  };
  '/twitter/check': {
    post: {
      parameters: {
        body: {
          root?: {
            /** 用户加密hash */
            hash: string;
            /** 校验数据 */
            data: string;
            /** 推文链接 */
            tweetUrl: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
                         * @description 52339 tg用户标识缺失
                         * 52340 用户不存在
                         * 52341 tg用户数据校验不通过
                         * 52342 推文链接解析失败
                         * 52343 用户操作太频繁
                         * 52344 校验不通过，未找到目标推文
                         * 52345 未知
                         * 52346 无提币记录
                         */
            code: string;
            message: string;
            /** 是否成功 */
            data: boolean;
          };
        };
      };
    };
  };
  '/twitter/check/query': {
    post: {
      parameters: {
        body: {
          root?: {
            /** 用户加密hash */
            hash: string;
            /** 校验data */
            data: string;
          };
        };
      };
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            message: string;
            /** 是否已校验成功 */
            data: boolean;
          };
        };
      };
    };
  };
  '/twitter/callback/get': {
    get: {
      parameters: {};
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string;
            message: string;
            /** 跳转链接 */
            data: string;
          };
        };
      };
    };
  };
}

export interface operations {
}

export interface external {
}

export type UserUsernameGetParams = paths['/user/username']['get']['parameters'];
export type UserUsername = paths['/user/username']['get']['responses'][200]['schema']['data'];
export type UserCheckGetParams = paths['/user/check']['get']['parameters']['query'];
export type UserCheck = paths['/user/check']['get']['responses'][200]['schema']['data'];
export type UserUserVoteDevicesGetParams = paths['/user/user-vote-devices']['get']['parameters']['query'];
export type UserUserVoteDevices = paths['/user/user-vote-devices']['get']['responses'][200]['schema']['data'];
export type UserUserRewardGetParams = paths['/user/user-reward']['get']['parameters']['query'];
export type UserUserReward = paths['/user/user-reward']['get']['responses'][200]['schema']['data'];
export type UserRegisterPostParams = paths['/user/register']['post']['parameters']['body']['root'];
export type UserRegisterPost = paths['/user/register']['post']['responses'][200]['schema']['data'];
export type UserInviterRecordsGetParams = paths['/user/inviter-records']['get']['parameters']['query'];
export type UserInviterRecords = paths['/user/inviter-records']['get']['responses'][200]['schema']['data'];
export type UserUserGetParams = paths['/user/user']['get']['parameters']['query'];
export type UserUser = paths['/user/user']['get']['responses'][200]['schema']['data'];
export type UserRewardRankGetParams = paths['/user/reward:rank']['get']['parameters']['query'];
export type UserRewardRank = paths['/user/reward:rank']['get']['responses'][200]['schema']['data'];
export type UserInviterRankFullGetParams = paths['/user/inviter/rank/full']['get']['parameters']['query'];
export type UserInviterRankFull = paths['/user/inviter/rank/full']['get']['responses'][200]['schema']['data'];
export type UserInviterRankWeekGetParams = paths['/user/inviter/rank/week']['get']['parameters']['query'];
export type UserInviterRankWeek = paths['/user/inviter/rank/week']['get']['responses'][200]['schema']['data'];
export type UserNotifyPostParams = paths['/user/notify']['post']['parameters']['body']['root'];
export type UserNotifyPost = paths['/user/notify']['post']['responses'][200]['schema']['data'];
export type UserVoteDevicesGetParams = paths['/user/vote:devices']['get']['parameters']['query'];
export type UserVoteDevices = paths['/user/vote:devices']['get']['responses'][200]['schema']['data'];
export type UserUserStrictPostParams = paths['/user/user/strict']['post']['parameters']['body']['root'];
export type UserUserStrictPost = paths['/user/user/strict']['post']['responses'][200]['schema']['data'];
export type UserVerifyPostParams = paths['/user/verify']['post']['parameters']['body']['root'];
export type UserVerifyPost = paths['/user/verify']['post']['responses'][200]['schema']['data'];
export type UserPersonalInfoPostParams = paths['/user/personal/info']['post']['parameters']['body']['root'];
export type UserPersonalInfoPost = paths['/user/personal/info']['post']['responses'][200]['schema']['data'];
export type UserChannelJoinedPostParams = paths['/user/channel/joined']['post']['parameters']['body']['root'];
export type UserChannelJoinedPost = paths['/user/channel/joined']['post']['responses'][200]['schema']['data'];
export type DrawCanWithdrawGetParams = paths['/draw/canWithdraw']['get']['parameters']['query'];
export type DrawCanWithdraw = paths['/draw/canWithdraw']['get']['responses'][200]['schema']['data'];
export type DrawDoPostParams = paths['/draw/do']['post']['parameters']['body']['root'];
export type DrawDoPost = paths['/draw/do']['post']['responses'][200]['schema']['data'];
export type DrawChanceGetParams = paths['/draw/chance']['get']['parameters']['query'];
export type DrawChance = paths['/draw/chance']['get']['responses'][200]['schema']['data'];
export type DrawRecordGetParams = paths['/draw/record']['get']['parameters']['query'];
export type DrawRecord = paths['/draw/record']['get']['responses'][200]['schema']['data'];
export type DrawWithdrawPostParams = paths['/draw/withdraw']['post']['parameters']['body']['root'];
export type DrawWithdrawPost = paths['/draw/withdraw']['post']['responses'][200]['schema']['data'];
export type DrawWithdrawRecordPostParams = paths['/draw/withdraw-record']['post']['parameters']['body']['root'];
export type DrawWithdrawRecordPost = paths['/draw/withdraw-record']['post']['responses'][200]['schema']['data'];
export type DrawVerifyChancePostParams = paths['/draw/verify/chance']['post']['parameters']['body']['root'];
export type DrawVerifyChancePost = paths['/draw/verify/chance']['post']['responses'][200]['schema']['data'];
export type StakeDoPostParams = paths['/stake/do']['post']['parameters']['body']['root'];
export type StakeDoPost = paths['/stake/do']['post']['responses'][200]['schema']['data'];
export type StakeUnlockPostParams = paths['/stake/unlock']['post']['parameters']['body']['root'];
export type StakeUnlockPost = paths['/stake/unlock']['post']['responses'][200]['schema']['data'];
export type TransferTblPostParams = paths['/transfer/tbl']['post']['parameters']['body']['root'];
export type TransferTblPost = paths['/transfer/tbl']['post']['responses'][200]['schema']['data'];
export type AssignmentListPostParams = paths['/assignment/list']['post']['parameters']['body']['root'];
export type AssignmentListPost = paths['/assignment/list']['post']['responses'][200]['schema']['data'];
export type AssignmentVersionGetParams = paths['/assignment/version']['get']['parameters'];
export type AssignmentVersion = paths['/assignment/version']['get']['responses'][200]['schema']['data'];
export type AssignmentDoPostParams = paths['/assignment/do']['post']['parameters']['body']['root'];
export type AssignmentDoPost = paths['/assignment/do']['post']['responses'][200]['schema']['data'];
export type AssignmentDailyDoPostParams = paths['/assignment/daily/do']['post']['parameters']['body']['root'];
export type AssignmentDailyDoPost = paths['/assignment/daily/do']['post']['responses'][200]['schema']['data'];
export type AssignmentDailyListPostParams = paths['/assignment/daily/list']['post']['parameters']['body']['root'];
export type AssignmentDailyListPost = paths['/assignment/daily/list']['post']['responses'][200]['schema']['data'];
export type AssignmentDailyAssignmentPostParams = paths['/assignment/daily/assignment']['post']['parameters']['body']['root'];
export type AssignmentDailyAssignmentPost = paths['/assignment/daily/assignment']['post']['responses'][200]['schema']['data'];
export type AssignmentDailyRepeatAssignmentPostParams = paths['/assignment/daily/repeat-assignment']['post']['parameters']['body']['root'];
export type AssignmentDailyRepeatAssignmentPost = paths['/assignment/daily/repeat-assignment']['post']['responses'][200]['schema']['data'];
export type TwitterCheckPostParams = paths['/twitter/check']['post']['parameters']['body']['root'];
export type TwitterCheckPost = paths['/twitter/check']['post']['responses'][200]['schema']['data'];
export type TwitterCheckQueryPostParams = paths['/twitter/check/query']['post']['parameters']['body']['root'];
export type TwitterCheckQueryPost = paths['/twitter/check/query']['post']['responses'][200]['schema']['data'];
export type TwitterCallbackGetGetParams = paths['/twitter/callback/get']['get']['parameters'];
export type TwitterCallbackGet = paths['/twitter/callback/get']['get']['responses'][200]['schema']['data'];
