/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/common/dict': {
    get: {
      parameters: {
        query: {
          dictCode: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string
            msg: string
            data: {
              code: string
              i18nName: string
              dictType: string
              description: string
              sort: string
              items: string[]
            }
            fail: boolean
          }
        }
      }
    }
  }
  '/reward/cross-reward:withdraw': {
    post: {
      parameters: {
        body: {
          root?: {
            /** @description evm地址 */
            address: string
            /** @description 提现金额 */
            withdrawAmount: number
            /** @description 项目方,BITGET、BOOL */
            from?: string
          }
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string
            msg: string
            data: unknown
            fail: boolean
          }
        }
      }
    }
  }
  '/reward/cross-reward': {
    get: {
      parameters: {
        query: {
          /** evm 地址 */
          address: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string
            msg: string
            data: {
              crossRewardID: string
              /** @description 奖励地址 */
              crossRewardAddress: string
              /** @description 总奖励金额 */
              crossRewardTotalReward: number
              /** @description 目前奖励金额 */
              crossRewardCurrentReward: number
              /** @description 已提现金额 */
              crossRewardWithdrawReward: number
              /** @description 此地址已跨链数量 */
              totalCrossCount: number
            }
            fail: boolean
          }
        }
      }
    }
  }
  '/user/address-integral': {
    get: {
      parameters: {}
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string
            msg: string
            data: {
              addressIntegralID: string
              addressIntegralAddress: string
              addressIntegralTotalIntegral: number
              addressIntegralCurrentIntegral: number
              addressIntegralSpentIntegral: number
              bridgeIntegral: number
              stakeIntegral: number
              socialIntegral: number
            }
            fail: boolean
          }
        }
      }
    }
  }
  '/user/integral-records': {
    get: {
      parameters: {
        query: {
          /** 积分类型 */
          type?: string
          pageNo: number
          pageSize: number
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string
            msg: string
            data: {
              items: {
                integralRecordID: string
                integralRecordAddress: string
                integralRecordChangeValue: number
                integralRecordBeforeIntegral: number
                integralRecordAfterIntegral: number
                integralRecordType: string
                integralRecordSettlementTime: number
                integralRecordRemark: string
              }[]
              pageNo: number
              pageSize: number
              totalPage: number
              totalCount: string
              hasPrev: boolean
              hasNext: boolean
            }
            fail: boolean
          }
        }
      }
    }
  }
  '/user/invitation-relation': {
    post: {
      parameters: {
        body: {
          root?: {
            /** @description 邀请码 */
            invitationCode: string
          }
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string
            msg: string
            data: unknown
            fail: boolean
          }
        }
      }
    }
  }
  '/user/user:check': {
    get: {
      parameters: {
        query: {
          address: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string
            msg: string
            data: boolean
            fail: boolean
          }
        }
      }
    }
  }
  '/user/address-integrals:top': {
    get: {
      parameters: {
        query: {
          /** 地址筛选 */
          address?: string
          pageNo: number
          pageSize: number
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string
            msg: string
            data: {
              items: {
                address: string
                inviter: string
                currentIntegral: number
                rank?: number
              }[]
              pageNo: number
              pageSize: number
              totalPage: number
              totalCount: string
              hasPrev: boolean
              hasNext: boolean
            }
            fail: boolean
          }
        }
      }
    }
  }
  '/user/user': {
    get: {
      parameters: {}
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string
            msg: string
            data: {
              userID: string
              /** @description 用户地址 */
              userAddress: string
              /** @description 用户邀请码 */
              userInvitationCode: string
              /** @description 用户邀请者地址 */
              inviterAddress: string
              /** @description 用户下级数量 */
              inviterCount: number
              /** @description 完成社区任务总数 */
              completedNum: string
              /** @description 用户积分排名 */
              rank: string
              /** @description 用户是否有邀请资格 */
              inviterQualified: boolean
            }
            fail: boolean
          }
        }
      }
    }
  }
  '/user/user:login': {
    post: {
      parameters: {
        body: {
          root?: {
            /** @description 地址 */
            address: string
            /** @description msg签名，可以在里面包含邀请码 */
            signature: string
            /** @description 邀请码 */
            invitationCode?: string
          }
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string
            msg: string
            data: string
            fail: boolean
          }
        }
      }
    }
  }
  '/user/dhc-record:sync': {
    post: {
      parameters: {}
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string
            msg: string
            data: { [key: string]: unknown }
            fail: boolean
          }
        }
      }
    }
  }
  '/user/task-record:sync': {
    post: {
      parameters: {}
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string
            msg: string
            data: { [key: string]: unknown }
            fail: boolean
          }
        }
      }
    }
  }
  '/api/bridge-records': {
    get: {
      parameters: {
        query: {
          /** evm地址 */
          address?: string
          /** 起始链txHash（仅支持EVM） */
          txHash?: string
          /** 链标识（起始链或目标链） */
          network?: string
          /** 页数 */
          pageNo: number
          /** 页码 */
          pageSize: number
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string
            msg: string
            data: {
              items: {
                /** @description evm地址 */
                address: string
                /** @description 起始链 */
                sourceChain: string
                /** @description 目标链 */
                destChain: string
                /** @description 跨链状态 */
                crossStatus: string
                /** @description 跨链桥类型 */
                crossType: string
                /** @description 跨链交易时间 */
                txTime: number
              }[]
              pageNo: number
              pageSize: number
              totalPage: number
              totalCount: string
              hasPrev: boolean
              hasNext: boolean
            }
            fail: boolean
          }
        }
      }
    }
  }
  '/api/bridge-address': {
    get: {
      parameters: {
        query: {
          /** evm地址 */
          address: string
          /** 项目方名称，例BOOL、BITGET */
          projectName: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string
            /** @description 提示信息 */
            msg: string
            data: {
              /** @description 是否使用过bool水龙头 */
              faucetUsed: boolean
              /** @description 是否使用过跨链桥 */
              bridgeUsed: boolean
            }
            /** @description 接口是否调用成功 */
            fail: boolean
          }
        }
      }
    }
  }
  '/api/bridge-statistics': {
    get: {
      parameters: {
        query: {
          /** evm地址 */
          address?: string
          /** 起始链txHash（仅支持EVM） */
          txHash?: string
          /** 链标识（起始链或目标链） */
          network?: string
          /** 页数 */
          pageNo: number
          /** 页码 */
          pageSize: number
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            code: string
            msg: string
            data: {
              items: {
                /** @description 地址 */
                address: string
                /** @description btc跨链交易数量 */
                btcBridgeCount: number
                /** @description evm跨链交易数量 */
                evmBridgeCount: number
                /** @description 当前奖励tbol */
                currentReward: number
                /** @description 已提现tbol */
                withdrawReward: number
              }[]
              pageNo: number
              pageSize: number
              totalPage: number
              totalCount: string
              hasPrev: boolean
              hasNext: boolean
            }
            fail: boolean
          }
        }
      }
    }
  }
}

export interface operations { }

export interface external { }

export type CommonDictGetParams = paths['/common/dict']['get']['parameters']['query']
export type CommonDict = paths['/common/dict']['get']['responses'][200]['schema']['data']
export type RewardCrossRewardWithdrawPostParams = paths['/reward/cross-reward:withdraw']['post']['parameters']['body']['root']
export type RewardCrossRewardWithdrawPost = paths['/reward/cross-reward:withdraw']['post']['responses'][200]['schema']['data']
export type RewardCrossRewardGetParams = paths['/reward/cross-reward']['get']['parameters']['query']
export type RewardCrossReward = paths['/reward/cross-reward']['get']['responses'][200]['schema']['data']
export type UserAddressIntegralGetParams = paths['/user/address-integral']['get']['parameters']
export type UserAddressIntegral = paths['/user/address-integral']['get']['responses'][200]['schema']['data']
export type UserIntegralRecordsGetParams = paths['/user/integral-records']['get']['parameters']['query']
export type UserIntegralRecords = paths['/user/integral-records']['get']['responses'][200]['schema']['data']
export type UserInvitationRelationPostParams = paths['/user/invitation-relation']['post']['parameters']['body']['root']
export type UserInvitationRelationPost = paths['/user/invitation-relation']['post']['responses'][200]['schema']['data']
export type UserUserCheckGetParams = paths['/user/user:check']['get']['parameters']['query']
export type UserUserCheck = paths['/user/user:check']['get']['responses'][200]['schema']['data']
export type UserAddressIntegralsTopGetParams = paths['/user/address-integrals:top']['get']['parameters']['query']
export type UserAddressIntegralsTop = paths['/user/address-integrals:top']['get']['responses'][200]['schema']['data']
export type UserUserGetParams = paths['/user/user']['get']['parameters']
export type UserUser = paths['/user/user']['get']['responses'][200]['schema']['data']
export type UserUserLoginPostParams = paths['/user/user:login']['post']['parameters']['body']['root']
export type UserUserLoginPost = paths['/user/user:login']['post']['responses'][200]['schema']['data']
export type UserDhcRecordSyncPostParams = paths['/user/dhc-record:sync']['post']['parameters']['body']['root']
export type UserDhcRecordSyncPost = paths['/user/dhc-record:sync']['post']['responses'][200]['schema']['data']
export type UserTaskRecordSyncPostParams = paths['/user/task-record:sync']['post']['parameters']['body']['root']
export type UserTaskRecordSyncPost = paths['/user/task-record:sync']['post']['responses'][200]['schema']['data']
export type ApiBridgeRecordsGetParams = paths['/api/bridge-records']['get']['parameters']['query']
export type ApiBridgeRecords = paths['/api/bridge-records']['get']['responses'][200]['schema']['data']
export type ApiBridgeAddressGetParams = paths['/api/bridge-address']['get']['parameters']['query']
export type ApiBridgeAddress = paths['/api/bridge-address']['get']['responses'][200]['schema']['data']
export type ApiBridgeStatisticsGetParams = paths['/api/bridge-statistics']['get']['parameters']['query']
export type ApiBridgeStatistics = paths['/api/bridge-statistics']['get']['responses'][200]['schema']['data']
